e-commerce-henry/backend-pf-e-commerce

- source/models/SaleBanner.js
se creo el modelo del banner con promociones en la db
> SaleBanner created

- package.json
- source/app.js
- source/controllers/Users/postUser.js
- source/db.js
- source/models/UserLoginDetail.js
- source/routes/index.js
- source/routes/postUser.js
Se creo el controller para manejar la creacion de un nuevo usuario. Se agrego la ruta a la carpeta routes. Falta implementar metodo de autenticacion
> Feature post user route

- package.json
- passport-config.js
- source/app.js
- source/controllers/Users/getUser.js
- source/routes/index.js
- source/routes/users.js
se implemento método de autenticación usando passport como dependencia y generando una estrategia local. Para ello se creo un archivo passport-config para establecer la configuración de passport. Se probaron algunas rutas simulando logueo de usuario para ver si funcionaba y parece andar bien. Seria necesario probar y debuguear cuando este listo el Front.
> Feature auth

- source/app.js
- source/controllers/Users/deleteUser.js
- source/controllers/Users/getUser.js
- source/routes/users.js
se creo ruta para borrar usuario.
> deleteUser route was created so the user can delete his/her account

- package.json
- source/app.js
ahora acepta el puerto 4000 del admin
> Add port access 4000

- index.js
- source/controllers/Users/postUser.js
- source/controllers/Wishlist/postFavItem.js
- source/db.js
- source/routes/index.js
- source/routes/wishlist.js
se creo ruta para agregar producto a la wishlist. En el proceso se edito la ruta de creacion de usuario para que cuando se genere un nuevo usuario se cree una wishlist automaticamente asociada a el mismo.
> Feature post fav item

- source/controllers/Wishlist/deleteFavItem.js
- source/routes/wishlist.js
se crea ruta para remover productos de la wishlist del usuario
> deleteFavItems route created

- source/controllers/Wishlist/getFavItem.js
- source/routes/wishlist.js
se agrega ruta para poder solicitar todos los productos que un usuario tiene en su wishlist.
> getFavItems to retrieve all products from user wishlist was done

- source/controllers/Cart/postCartItem.js
- source/controllers/Users/postUser.js
- source/models/Cart.js
- source/routes/cart.js
- source/routes/index.js
se modifica modelo Cart cambiando el cambo "total" por "name", se crea ruta para poder agregar un producto al carrito de compra del usuario.
> Feature post cart item route

- source/controllers/Cart/delelteCartItem.js
- source/routes/cart.js
ruta para remover un producto del carrito creada
> delete Cart Item Route created

- source/controllers/Cart/getCartItem.js
- source/controllers/Wishlist/getFavItem.js
- source/routes/cart.js
se crea ruta para solicitar todos los productos del carrito de un usuario
> get CartItem route created

- source/controllers/Wishlist/deleteFavItem.js
- source/controllers/Wishlist/postFavItem.js
se modificaron archivos postFavItem.js y deleteFavItem.js para mejorar un poco el codigo
> Refactor delete fav item

- source/controllers/Order/getHistoryUser.js
- source/routes/order.js
- source/routes/users.js
> route get history

- source/controllers/ClientAddress/deleteClientAddress.js
- source/controllers/ClientAddress/editClientAddress.js
- source/controllers/ClientAddress/postClientAddress.js
- source/controllers/Users/editUser.js
- source/db.js
- source/routes/clientAddress.js
- source/routes/index.js
-se cambio relacion entre modelo user y modelo ClientAddres de manera que el usuario pueda guardar mas de una direccion.
- se creo ruta postClientAddres para poder agregar otra direccion en el perfil del usuario
- se creo ruta editClientAddres para poder editar las direcciones del cliente
- se creo ruta deleteClientAddress para poder eliminar direcciones del cliente.
> Fix client address

- source/controllers/Users/getUserById.js
- source/controllers/Users/getUsers.js
- source/routes/users.js
-se crea ruta getUsers para obtener todos los usuarios
-se crea ruta getUserById para obtener un usario por Id
> Feat get users route

- source/controllers/SaleBanner/DeleteSaleBanner.js
- source/controllers/SaleBanner/GetSaleBanner.js
- source/controllers/SaleBanner/PostSaleBanner.js
- source/models/SaleBanner.js
- source/routes/saleBanner.js
se modificaron algunas rutas del Sale banner para poder buscar los productos guardados en dicha tabla desde el panel del administrador y se agrego nueva ruta para borrar de la db productos de la misma.
> sale banner routes modified to set Salebanner panel in admin controls

- source/routes/products.js
> Update controller product

- source/controllers/Users/editUser.js
- source/controllers/Users/getUserById.js
- source/controllers/Users/getUsers.js
- source/controllers/Users/postUser.js
se creo el panel de usuarios del lado del administrador para que el admin pueda crear, borrar y editar usuarios
> Feat userspanel admin

- source/controllers/Order/postOrder.js
- source/models/Order.js
- source/models/Orderdetail.js
- source/routes/index.js
- source/routes/order.js
se creo ruta para crear una orden al "despachar" el carrito de compra.
> postOrder route created- related DB models modified

- source/controllers/Order/editOrder.js
- source/controllers/Order/postOrder.js
- source/controllers/Wishlist/deleteFavItem.js
- source/models/Order.js
- source/routes/order.js
-se agrega campo shipping status en modelo de orden para llevar un tracking del proceso de envio del producto. Los valores que admite son "sent" y "not sent(default)" (enviado y no enviado).
- Se crea ruta para editar la orden de compra una vez que recibe la respuesta de mercadopago y para modificar el estado de envio.
> Fix order model

- source/controllers/Auth/signIn.js
se cambia la forma de guardar el token en el front de cookies a localSotrage para probar si en deploy funciona.
> changed JWT storage from cookies to localStorage

- index.js
- source/controllers/Auth/logOut.js
- source/controllers/Auth/signIn.js
- source/controllers/Products/Editproduct.js
- source/controllers/Products/PostProduct.js
- source/middleware/authMiddleware.js
- source/routes/auth.js
- source/routes/categories.js
- source/routes/order.js
- source/routes/products.js
- source/routes/saleBanner.js
- source/routes/users.js
Luego de probar Firebase debido al problema de las cookies, se vuelve a implementar JWT guardandolos en sessionStorage. 
Se protegen rutas del back para comprobar que el usuario este logueado y cuando se requiera, sea administrador.
> Feat auth4

- source/controllers/Users/postUser.js
- source/routes/users.js
se arregla bug al editar usuarios en panel admin
> Fix adminusers bug

- source/models/ClientAddress.js
- source/models/User.js
- source/models/UserLoginDetail.js
se eliminan restricciones para que puedan entrar valores nulos en tabla de usuarios para que pueda iniciar sesion con Google
> elimino restricciones de tabla de usuario en DB

- package.json
- source/controllers/Auth/googleAuth.js
- source/controllers/Auth/signUp.js
- source/routes/auth.js
se implementa google login. Se crea controller y ruta en el back para manejar el logue o registro con google.
> implemented GoogleLogin

- package.json
- source/controllers/Cart/postCartItem.js
- source/controllers/MercadoPago/getInfoPay.js
- source/controllers/MercadoPago/mercadopago.js
- source/controllers/Order/postOrder.js
- source/models/CartItem.js
- source/models/Orderdetail.js
- source/routes/index.js
- source/routes/mercadoPago.js
tratando de implementar mercado pago.
> Feat mercado pago

- source/controllers/MercadoPago/getInfoPay.js
- source/controllers/MercadoPago/mercadopago.js
- source/controllers/Order/getOrderById.js
- source/routes/order.js
-Se trabaja sobre la implementacion de mercado pago
-se agrega una ruta getOrderById para facilitar la obtencion de data en el panel de administrador para desplegar informacion detallada de la orden.
> Fix mercado pago

- source/controllers/MercadoPago/getInfoPay.js
- source/controllers/MercadoPago/mercadopago.js
- source/controllers/Order/postOrder.js
se agrega funcion para que actualice el stock en la base de datos cuando la compra es exitosa
> Fix stock update
